const characterData = [
  /* =========================
     MAIN TRIO
  ========================= */
  {
    id: "harry-potter",
    number: "001",
    name: "Harry Potter",
    title: "The Boy Who Lived",
    portrait: "/images/characters/harry-potter.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: {
      house: "Gryffindor",
      species: "Human",
      bloodStatus: "Half-blood",
      born: "31 July 1980",
      occupation: "Student · Auror",
      affiliation: "Hogwarts · Dumbledore's Army · Order of the Phoenix",
      wand: "Holly, phoenix feather, 11 inches",
      patronus: "Stag",
      family: "Potter Family",
    },
    introduction: "A young wizard who survived Voldemort's attack as a baby and later became one of the most important people in the fight against him.",
    personality: "Harry is brave, loyal and strongly protective of the people he cares about. He can be impulsive and stubborn, but he repeatedly chooses to stand against danger.",
    story: [
      { year: "1991", label: "FIRST YEAR", title: "The Wizarding World Opens", text: "Harry learns that he is a wizard and begins his first year at Hogwarts." },
      { year: "1992", label: "SECOND YEAR", title: "The Chamber of Secrets", text: "Harry discovers the truth about the Chamber of Secrets and Tom Riddle." },
      { year: "1993", label: "THIRD YEAR", title: "The Prisoner of Azkaban", text: "Harry discovers the truth about Sirius Black and his parents." },
      { year: "1994", label: "FOURTH YEAR", title: "The Triwizard Tournament", text: "Harry is entered into the tournament and witnesses Voldemort's return." },
      { year: "1995", label: "FIFTH YEAR", title: "Dumbledore's Army", text: "Harry leads Dumbledore's Army to teach students defensive magic." },
      { year: "1996", label: "SIXTH YEAR", title: "The Horcrux Secret", text: "Harry investigates Voldemort's past alongside Dumbledore." },
      { year: "1997", label: "THE HUNT", title: "The Hunt for the Horcruxes", text: "Harry leaves Hogwarts to hunt Voldemort's Horcruxes." },
      { year: "1998", label: "THE BATTLE", title: "The Battle of Hogwarts", text: "Harry defeats Voldemort in the final confrontation." }
    ],
    relationships: [
      { id: "ron-weasley", name: "Ron Weasley", type: "Best Friend", image: "/images/characters/ron-weasley.jpg" },
      { id: "hermione-granger", name: "Hermione Granger", type: "Best Friend", image: "/images/characters/hermione-granger.jpg" }
    ],
    magic: [
      { name: "Holly Wand", type: "WAND" },
      { name: "Stag Patronus", type: "PATRONUS" }
    ],
    legacy: "Defined by his choices, bravery, and self-sacrifice in the face of absolute darkness."
  },
  {
    id: "hermione-granger",
    number: "002",
    name: "Hermione Granger",
    title: "Brightest Witch of Her Age",
    portrait: "/images/characters/hermione-granger.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: {
      house: "Gryffindor",
      species: "Human",
      bloodStatus: "Muggle-born",
      born: "19 September 1979",
      occupation: "Student · Ministry Official",
      affiliation: "Hogwarts · Dumbledore's Army · S.P.E.W.",
      wand: "Vine wood, dragon heartstring, 10¾ inches",
      patronus: "Otter",
      family: "Granger Family",
    },
    introduction: "A brilliant and hardworking witch whose knowledge and quick thinking repeatedly help Harry and Ron.",
    personality: "Logical, deeply principled, fiercely intelligent, and immensely devoted to her friends.",
    story: [
      { year: "1991", label: "FIRST YEAR", title: "Hogwarts Arrival", text: "Proves her extraordinary intelligence and forms a core friendship with Harry and Ron." },
      { year: "1997", label: "THE HUNT", title: "Horcrux Quest", text: "Protects the trio with defensive enchantments while hunting Horcruxes." }
    ],
    relationships: [
      { id: "harry-potter", name: "Harry Potter", type: "Best Friend", image: "/images/characters/harry-potter.jpg" },
      { id: "ron-weasley", name: "Ron Weasley", type: "Love & Family", image: "/images/characters/ron-weasley.jpg" }
    ],
    magic: [
      { name: "Vine Wood Wand", type: "WAND" },
      { name: "Otter Patronus", type: "PATRONUS" }
    ],
    legacy: "Proved that brilliance, logic, and unwavering loyalty are as vital as physical power."
  },
  {
    id: "ron-weasley",
    number: "003",
    name: "Ron Weasley",
    title: "Loyal Companion",
    portrait: "/images/characters/ron-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: {
      house: "Gryffindor",
      species: "Human",
      bloodStatus: "Pure-blood",
      born: "1 March 1980",
      occupation: "Student · Auror · Shop Owner",
      affiliation: "Hogwarts · Dumbledore's Army · Order of the Phoenix",
      wand: "Willow, unicorn hair, 14 inches",
      patronus: "Jack Russell Terrier",
      family: "Weasley Family",
    },
    introduction: "Harry's best friend and a loyal member of the Weasley family who stands beside his friends through dangerous times.",
    personality: "Humorous, strategic, quick to defend his loved ones, though occasionally battling self-doubt.",
    story: [
      { year: "1991", label: "FIRST YEAR", title: "Chess Master", text: "Sacrifices himself in a giant game of Wizard's Chess to allow Harry to advance." },
      { year: "1998", label: "THE BATTLE", title: "Battle of Hogwarts", text: "Destroys a Horcrux and fights to protect his family and school." }
    ],
    relationships: [
      { id: "harry-potter", name: "Harry Potter", type: "Best Friend", image: "/images/characters/harry-potter.jpg" },
      { id: "hermione-granger", name: "Hermione Granger", type: "Love & Family", image: "/images/characters/hermione-granger.jpg" }
    ],
    magic: [
      { name: "Willow Wand", type: "WAND" },
      { name: "Jack Russell Patronus", type: "PATRONUS" }
    ],
    legacy: "Demonstrated that true bravery comes from overcoming insecurity for the people you love."
  },

  /* =========================
     GRYFFINDOR
  ========================= */
  {
    id: "neville-longbottom",
    number: "004",
    name: "Neville Longbottom",
    title: "Defender of Hogwarts",
    portrait: "/images/characters/neville-longbottom.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "30 July 1980", occupation: "Herbology Professor", affiliation: "Dumbledore's Army", wand: "Cherry, unicorn hair", patronus: "Non-corporeal", family: "Longbottom Family" },
    introduction: "A shy student who grows into a courageous young wizard and becomes an important defender of Hogwarts.",
    personality: "Modest, resilient, humble, and fiercely brave when pushed to stand up for justice.",
    story: [{ year: "1998", label: "THE BATTLE", title: "Slaying Nagini", text: "Draws Gryffindor's Sword and slays Voldemort's final Horcrux." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Friend", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Sword of Gryffindor", type: "MAGICAL OBJECT" }],
    legacy: "Showed that courage is not the absence of fear, but the willingness to stand up anyway."
  },
  {
    id: "ginny-weasley",
    number: "005",
    name: "Ginny Weasley",
    title: "Quidditch Star & DA Leader",
    portrait: "/images/characters/ginny-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "11 August 1981", occupation: "Quidditch Player · Journalist", affiliation: "Dumbledore's Army", wand: "Yew", patronus: "Horse", family: "Weasley Family" },
    introduction: "Ron's younger sister, a talented witch and Quidditch player who becomes an important member of Dumbledore's Army.",
    personality: "Fierce, independent, witty, and exceptionally tough under pressure.",
    story: [{ year: "1992", label: "SECOND YEAR", title: "Chamber of Secrets", text: "Survives being possessed by Tom Riddle's diary." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Love & Family", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Bat-Bogey Hex", type: "SPELL" }],
    legacy: "Overcame early trauma to become a fierce warrior and accomplished wizard."
  },
  {
    id: "fred-weasley",
    number: "006",
    name: "Fred Weasley",
    title: "Prankster & Inventor",
    portrait: "/images/characters/fred-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "1 April 1978", occupation: "Shop Owner", affiliation: "Order of the Phoenix · Dumbledore's Army", wand: "Unknown", patronus: "Magpie", family: "Weasley Family" },
    introduction: "One of the Weasley twins, famous for magical jokes, inventions and causing trouble with his brother George.",
    personality: "Bold, inventive, humorous, and fearless in challenging authority.",
    story: [{ year: "1996", label: "ESCAPE", title: "Leaving Hogwarts", text: "Stages an legendary rebellion against Umbridge and opens Weasleys' Wizard Wheezes." }],
    relationships: [{ id: "george-weasley", name: "George Weasley", type: "Twin Brother", image: "/images/characters/george-weasley.jpg" }],
    magic: [{ name: "Marauder's Map", type: "MAGICAL OBJECT" }],
    legacy: "Brought laughter and joy to the wizarding world even in its darkest hours."
  },
  {
    id: "george-weasley",
    number: "007",
    name: "George Weasley",
    title: "Prankster & Entrepreneur",
    portrait: "/images/characters/george-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "1 April 1978", occupation: "Shop Owner", affiliation: "Order of the Phoenix · Dumbledore's Army", wand: "Unknown", patronus: "Magpie", family: "Weasley Family" },
    introduction: "Fred's twin brother and partner in magical mischief, later helping create Weasleys' Wizard Wheezes.",
    personality: "Creative, warm, resilient, and quick-witted.",
    story: [{ year: "1997", label: "SEVEN POTTERS", title: "Battle of the Seven Potters", text: "Loses his ear during an ambush by Death Eaters." }],
    relationships: [{ id: "fred-weasley", name: "Fred Weasley", type: "Twin Brother", image: "/images/characters/fred-weasley.jpg" }],
    magic: [{ name: "Weasleys' Wizard Wheezes Products", type: "MAGICAL OBJECT" }],
    legacy: "Continued spreading joy and innovation in memory of his brother."
  },
  {
    id: "percy-weasley",
    number: "008",
    name: "Percy Weasley",
    title: "Ministry Official",
    portrait: "/images/characters/percy-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "22 August 1976", occupation: "Head of Magical Transportation", affiliation: "Ministry of Magic", wand: "Unknown", patronus: "Non-corporeal", family: "Weasley Family" },
    introduction: "An ambitious and serious member of the Weasley family who becomes strongly focused on his Ministry career.",
    personality: "Rule-bound, ambitious, formal, but ultimately dedicated to doing what is right.",
    story: [{ year: "1998", label: "REDEMPTION", title: "Battle of Hogwarts", text: "Reconciles with his family and fights against the Death Eaters." }],
    relationships: [{ id: "ron-weasley", name: "Ron Weasley", type: "Brother", image: "/images/characters/ron-weasley.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Proved that it is never too late to admit mistakes and protect family."
  },
  {
    id: "seamus-finnigan",
    number: "009",
    name: "Seamus Finnigan",
    title: "Pyrotechnic Wizard",
    portrait: "/images/characters/seamus-finnigan.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Half-blood", born: "1980", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Fox", family: "Finnigan Family" },
    introduction: "A Gryffindor student in Harry's year who eventually helps defend Hogwarts against Voldemort's forces.",
    personality: "Hot-headed, explosive enthusiast, loyal friend once convinced of truth.",
    story: [{ year: "1998", label: "DEFENSE", title: "Blowing Up the Bridge", text: "Uses his penchant for pyrotechnics to destroy the wooden bridge during the battle." }],
    relationships: [{ id: "dean-thomas", name: "Dean Thomas", type: "Best Friend", image: "/images/characters/dean-thomas.jpg" }],
    magic: [{ name: "Fox Patronus", type: "PATRONUS" }],
    legacy: "Stood firm in defense of Hogwarts when the dark forces attacked."
  },
  {
    id: "dean-thomas",
    number: "010",
    name: "Dean Thomas",
    title: "Artist & Rebel",
    portrait: "/images/characters/dean-thomas.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Half-blood", born: "1980", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Non-corporeal", family: "Thomas Family" },
    introduction: "A friendly Gryffindor student who joins Dumbledore's Army and later fights against Voldemort.",
    personality: "Artistic, easygoing, courageous, and loyal.",
    story: [{ year: "1997", label: "RUNAWAY", title: "On the Run", text: "Evades Snatchers as a muggle-born fugitive before joining the Hogwarts battle." }],
    relationships: [{ id: "seamus-finnigan", name: "Seamus Finnigan", type: "Best Friend", image: "/images/characters/seamus-finnigan.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Fought bravely for equality in the wizarding world."
  },
  {
    id: "lavender-brown",
    number: "011",
    name: "Lavender Brown",
    title: "Gryffindor Defender",
    portrait: "/images/characters/lavender-brown.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "1979", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Non-corporeal", family: "Brown Family" },
    introduction: "A Gryffindor student who enjoys Divination and later has a romantic relationship with Ron.",
    personality: "Emotional, expressive, romantic, and resilient.",
    story: [{ year: "1998", label: "THE BATTLE", title: "Battle of Hogwarts", text: "Fought bravely in the final battle to defend her school." }],
    relationships: [{ id: "ron-weasley", name: "Ron Weasley", type: "Ex-Boyfriend", image: "/images/characters/ron-weasley.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Remembered for her courage in joining Dumbledore's Army."
  },
  {
    id: "cormac-mclaggen",
    number: "012",
    name: "Cormac McLaggen",
    title: "Quidditch Keeper",
    portrait: "/images/characters/cormac-mclaggen.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "1979", occupation: "Student", affiliation: "Slug Club", wand: "Unknown", patronus: "Non-corporeal", family: "McLaggen Family" },
    introduction: "A confident and competitive Gryffindor who tries to earn a place on the house Quidditch team.",
    personality: "Arrogant, assertive, boastful, but strong-willed.",
    story: [{ year: "1996", label: "SIXTH YEAR", title: "Quidditch Trials", text: "Competes against Ron for the role of Gryffindor Keeper." }],
    relationships: [{ id: "hermione-granger", name: "Hermione Granger", type: "Yule Date", image: "/images/characters/hermione-granger.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "A bold Gryffindor who always asserted his presence."
  },
  {
    id: "oliver-wood",
    number: "013",
    name: "Oliver Wood",
    title: "Quidditch Captain",
    portrait: "/images/characters/oliver-wood.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "1975", occupation: "Professional Quidditch Player", affiliation: "Puddlemere United", wand: "Unknown", patronus: "Non-corporeal", family: "Wood Family" },
    introduction: "The passionate captain and Keeper of the Gryffindor Quidditch team during Harry's early Hogwarts years.",
    personality: "Single-minded, dedicated, passionate, and driven.",
    story: [{ year: "1993", label: "VICTORY", title: "Quidditch Cup", text: "Leads Gryffindor to win the Quidditch Cup after years of training." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Teammate", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Quidditch Gear", type: "EQUIPMENT" }],
    legacy: "Set the benchmark for Gryffindor Quidditch dedication and leadership."
  },
  {
    id: "colin-creevey",
    number: "014",
    name: "Colin Creevey",
    title: "Enthusiastic Photographer",
    portrait: "/images/characters/colin-creevey.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Muggle-born", born: "1981", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Non-corporeal", family: "Creevey Family" },
    introduction: "A younger Gryffindor who greatly admires Harry and loves taking magical photographs.",
    personality: "Excitable, energetic, loyal, and fearless.",
    story: [{ year: "1998", label: "HEROISM", title: "Battle of Hogwarts", text: "Sneaks back into Hogwarts to fight despite being underage." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Idol", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Magical Camera", type: "MAGICAL OBJECT" }],
    legacy: "Gave his life bravely in defense of Hogwarts."
  },
  {
    id: "parvati-patil",
    number: "015",
    name: "Parvati Patil",
    title: "DA Member",
    portrait: "/images/characters/parvati-patil.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "1980", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Tiger", family: "Patil Family" },
    introduction: "A Gryffindor student, Padma's twin sister and later a member of Dumbledore's Army.",
    personality: "Sociable, fond of Divination, and courageous.",
    story: [{ year: "1994", label: "YULE BALL", title: "Yule Ball Date", text: "Attends the Yule Ball as Harry Potter's date." }],
    relationships: [{ id: "padma-patil", name: "Padma Patil", type: "Twin Sister", image: "/images/characters/padma-patil.jpg" }],
    magic: [{ name: "Tiger Patronus", type: "PATRONUS" }],
    legacy: "Fought alongside her peers to overthrow Voldemort's regime."
  },

  /* =========================
     SLYTHERIN
  ========================= */
  {
    id: "draco-malfoy",
    number: "016",
    name: "Draco Malfoy",
    title: "Slytherin Rival",
    portrait: "/images/characters/draco-malfoy.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "5 June 1980", occupation: "Student", affiliation: "Death Eaters", wand: "Hawthorn, unicorn hair, 10 inches", patronus: "None", family: "Malfoy Family" },
    introduction: "Harry's school rival, raised in a wealthy pure-blood family whose beliefs strongly influence his childhood.",
    personality: "Proud, conflicted, prejudiced initially, but deeply burdened by high expectations.",
    story: [{ year: "1996", label: "TASK", title: "The Tower Task", text: "Given a dark mission by Voldemort, revealing his underlying conflict." }],
    relationships: [{ id: "lucius-malfoy", name: "Lucius Malfoy", type: "Father", image: "/images/characters/lucius-malfoy.jpg" }],
    magic: [{ name: "Hawthorn Wand", type: "WAND" }],
    legacy: "A tragic figure who eventually broke free from his family's dark legacy."
  },
  {
    id: "vincent-crabbe",
    number: "017",
    name: "Vincent Crabbe",
    title: "Slytherin Enforcer",
    portrait: "/images/characters/vincent-crabbe.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "1980", occupation: "Student", affiliation: "Death Eaters", wand: "Unknown", patronus: "None", family: "Crabbe Family" },
    introduction: "A Slytherin student and one of Draco Malfoy's closest companions.",
    personality: "Aggressive, foolish, easily led, and malicious.",
    story: [{ year: "1998", label: "FIENDFYRE", title: "Room of Requirement", text: "Unleashes uncontrollable Fiendfyre magic during the Battle of Hogwarts." }],
    relationships: [{ id: "draco-malfoy", name: "Draco Malfoy", type: "Leader", image: "/images/characters/draco-malfoy.jpg" }],
    magic: [{ name: "Fiendfyre Curse", type: "DARK MAGIC" }],
    legacy: "Fell victim to his own reckless dark magic."
  },
  {
    id: "gregory-goyle",
    number: "018",
    name: "Gregory Goyle",
    title: "Slytherin Muscle",
    portrait: "/images/characters/gregory-goyle.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "1980", occupation: "Student", affiliation: "Death Eaters", wand: "Unknown", patronus: "None", family: "Goyle Family" },
    introduction: "A physically strong Slytherin student who usually stays close to Draco and Crabbe.",
    personality: "Slow-witted, intimidating, obedient to Draco.",
    story: [{ year: "1998", label: "RESCUE", title: "Saved by Harry", text: "Rescued by Harry Potter from the Fiendfyre inferno." }],
    relationships: [{ id: "draco-malfoy", name: "Draco Malfoy", type: "Leader", image: "/images/characters/draco-malfoy.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Served as heavy enforcement for Slytherin's dark inner circle."
  },
  {
    id: "pansy-parkinson",
    number: "019",
    name: "Pansy Parkinson",
    title: "Slytherin Prefect",
    portrait: "/images/characters/pansy-parkinson.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "1979/1980", occupation: "Student", affiliation: "Inquisitorial Squad", wand: "Unknown", patronus: "None", family: "Parkinson Family" },
    introduction: "A Slytherin student who is close to Draco and often behaves cruelly toward Harry and his friends.",
    personality: "Spiteful, dominant, self-serving, and sharp-tongued.",
    story: [{ year: "1998", label: "SURRENDER", title: "Demand for Harry", text: "Advocates handing Harry over to Voldemort before the Battle of Hogwarts." }],
    relationships: [{ id: "draco-malfoy", name: "Draco Malfoy", type: "Friend", image: "/images/characters/draco-malfoy.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Embodied the dark self-preservation of old pure-blood ideals."
  },
  {
    id: "blaise-zabini",
    number: "020",
    name: "Blaise Zabini",
    title: "Slug Club Member",
    portrait: "/images/characters/blaise-zabini.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "1980", occupation: "Student", affiliation: "Slug Club", wand: "Unknown", patronus: "None", family: "Zabini Family" },
    introduction: "A wealthy Slytherin student in Harry's year who becomes part of Professor Slughorn's Slug Club.",
    personality: "Aloof, vain, aristocratic, and independent.",
    story: [{ year: "1996", label: "EXPRESS", title: "Hogwarts Express", text: "Invited to Horace Slughorn's compartment due to his famous mother." }],
    relationships: [{ id: "draco-malfoy", name: "Draco Malfoy", type: "Classmate", image: "/images/characters/draco-malfoy.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Maintained a cool detachment from both sides of the wizarding war."
  },

  /* =========================
     RAVENCLAW
  ========================= */
  {
    id: "luna-lovegood",
    number: "021",
    name: "Luna Lovegood",
    title: "Unique Visionary",
    portrait: "/images/characters/luna-lovegood.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Pure-blood", born: "13 February 1981", occupation: "Magizoologist", affiliation: "Dumbledore's Army", wand: "Acorn wood", patronus: "Hare", family: "Lovegood Family" },
    introduction: "A kind and unusual witch whose loyalty, courage and open mind make her one of Harry's trusted friends.",
    personality: "Eccentric, calm, deeply perceptive, unbothered by criticism.",
    story: [{ year: "1995", label: "THESTRAL", title: "Seeing Thestrals", text: "Bonded with Harry over their shared ability to see Thestrals." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Close Friend", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Hare Patronus", type: "PATRONUS" }],
    legacy: "Taught others that being different is a strength, not a flaw."
  },
  {
    id: "cho-chang",
    number: "022",
    name: "Cho Chang",
    title: "Ravenclaw Seeker",
    portrait: "/images/characters/cho-chang.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "1979", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Swan", family: "Chang Family" },
    introduction: "A Ravenclaw student and talented Quidditch player for whom Harry develops romantic feelings.",
    personality: "Gentle, emotional, popular, and loyal.",
    story: [{ year: "1995", label: "DA", title: "Dumbledore's Army", text: "Joins the DA to honor Cedric Diggory's memory." }],
    relationships: [{ id: "cedric-diggory", name: "Cedric Diggory", type: "Late Boyfriend", image: "/images/characters/cedric-diggory.jpg" }],
    magic: [{ name: "Swan Patronus", type: "PATRONUS" }],
    legacy: "Stood up against dark forces despite personal grief."
  },
  {
    id: "padma-patil",
    number: "023",
    name: "Padma Patil",
    title: "Ravenclaw Prefect",
    portrait: "/images/characters/padma-patil.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "1980", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Non-corporeal", family: "Patil Family" },
    introduction: "Parvati's twin sister and a Ravenclaw student who attends the Yule Ball with Ron.",
    personality: "Academic, quiet, observant, and brave.",
    story: [{ year: "1994", label: "YULE BALL", title: "Yule Ball Date", text: "Attends the ball as Ron Weasley's date." }],
    relationships: [{ id: "parvati-patil", name: "Parvati Patil", type: "Twin Sister", image: "/images/characters/parvati-patil.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "A key student fighter in Dumbledore's Army."
  },

  /* =========================
     HUFFLEPUFF
  ========================= */
  {
    id: "cedric-diggory",
    number: "024",
    name: "Cedric Diggory",
    title: "Triwizard Champion",
    portrait: "/images/characters/cedric-diggory.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Hufflepuff", species: "Human", bloodStatus: "Pure-blood", born: "1977", occupation: "Student", affiliation: "Hogwarts Champions", wand: "Ash, unicorn hair, 12¼ inches", patronus: "None", family: "Diggory Family" },
    introduction: "A respected and talented Hogwarts student chosen to represent the school in the Triwizard Tournament.",
    personality: "Honorable, modest, fair-minded, and exceptionally brave.",
    story: [{ year: "1995", label: "GRAVEYARD", title: "Tragic Fate", text: "Murdered by Peter Pettigrew under Voldemort's order in the Little Hangleton graveyard." }],
    relationships: [{ id: "cho-chang", name: "Cho Chang", type: "Girlfriend", image: "/images/characters/cho-chang.jpg" }],
    magic: [{ name: "Ash Wand", type: "WAND" }],
    legacy: "His tragic death united Hogwarts and signaled the dark return of Voldemort."
  },
  {
    id: "hannah-abbott",
    number: "025",
    name: "Hannah Abbott",
    title: "Hufflepuff Prefect",
    portrait: "/images/characters/hannah-abbott.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Hufflepuff", species: "Human", bloodStatus: "Half-blood", born: "1980", occupation: "Landlady of Leaky Cauldron", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Non-corporeal", family: "Abbott Family" },
    introduction: "A Hufflepuff student in Harry's year who later becomes a member of Dumbledore's Army.",
    personality: "Kind, anxious under extreme stress, but fiercely loyal.",
    story: [{ year: "1998", label: "DEFENSE", title: "Battle of Hogwarts", text: "Fought to defend Hogwarts as part of Dumbledore's Army." }],
    relationships: [{ id: "neville-longbottom", name: "Neville Longbottom", type: "Husband", image: "/images/characters/neville-longbottom.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Represented the core Hufflepuff values of loyalty and hard work."
  },
  {
    id: "justin-finch-fletchley",
    number: "026",
    name: "Justin Finch-Fletchley",
    title: "Muggle-born DA Member",
    portrait: "/images/characters/justin-finch-fletchley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Hufflepuff", species: "Human", bloodStatus: "Muggle-born", born: "1980", occupation: "Student", affiliation: "Dumbledore's Army", wand: "Unknown", patronus: "Non-corporeal", family: "Finch-Fletchley Family" },
    introduction: "A Muggle-born Hufflepuff student who later joins Dumbledore's Army.",
    personality: "Affable, proud of his heritage, enthusiastic.",
    story: [{ year: "1992", label: "PETRIFIED", title: "Basilisk Attack", text: "Petrified by the Basilisk through Nearly Headless Nick." }],
    relationships: [{ id: "hannah-abbott", name: "Hannah Abbott", type: "Housemate", image: "/images/characters/hannah-abbott.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "Overcame fears of dark magic to stand up against Death Eaters."
  },

  /* =========================
     HOGWARTS STAFF
  ========================= */
  {
    id: "albus-dumbledore",
    number: "027",
    name: "Albus Dumbledore",
    title: "Headmaster of Hogwarts",
    portrait: "/images/characters/albus-dumbledore.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Half-blood", born: "August 1881", occupation: "Headmaster", affiliation: "Order of the Phoenix", wand: "Elder Wand, 15 inches", patronus: "Phoenix", family: "Dumbledore Family" },
    introduction: "The wise and powerful headmaster of Hogwarts who becomes one of Harry's most important mentors.",
    personality: "Profoundly wise, eccentric, enigmatic, burdened by past mistakes.",
    story: [{ year: "1996", label: "MINISTRY", title: "Atrium Duel", text: "Duels Lord Voldemort at the Ministry of Magic." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Protege", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Elder Wand", type: "DEATHLY HALLOWS" }, { name: "Phoenix Patronus", type: "PATRONUS" }],
    legacy: "Architect of Lord Voldemort's ultimate downfall."
  },
  {
    id: "minerva-mcgonagall",
    number: "028",
    name: "Minerva McGonagall",
    title: "Head of Gryffindor",
    portrait: "/images/characters/minerva-mcgonagall.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Half-blood", born: "4 October 1935", occupation: "Transfiguration Professor · Headmistress", affiliation: "Order of the Phoenix", wand: "Fir, dragon heartstring, 9½ inches", patronus: "Cat", family: "McGonagall Family" },
    introduction: "A strict but caring professor, head of Gryffindor House and one of Hogwarts' strongest defenders.",
    personality: "Disciplined, formidable, fiercely protective, deeply resilient.",
    story: [{ year: "1998", label: "DEFENSE", title: "Piertotum Locomotor", text: "Animates Hogwarts statues to defend the castle against the dark army." }],
    relationships: [{ id: "albus-dumbledore", name: "Albus Dumbledore", type: "Ally & Friend", image: "/images/characters/albus-dumbledore.jpg" }],
    magic: [{ name: "Animagus Transformation", type: "TRANSFIGURATION" }],
    legacy: "The steady shield and heart of Hogwarts School."
  },
  {
    id: "severus-snape",
    number: "029",
    name: "Severus Snape",
    title: "Potions Master & Double Agent",
    portrait: "/images/characters/severus-snape.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Half-blood", born: "9 January 1960", occupation: "Potions Professor · Headmaster", affiliation: "Order of the Phoenix · Death Eaters", wand: "Unknown", patronus: "Doe", family: "Prince / Snape Family" },
    introduction: "A highly skilled and mysterious professor whose true loyalties become central to Harry's story.",
    personality: "Sarcastic, secretive, intensely focused, tragic, motivated by love.",
    story: [{ year: "1998", label: "MEMORIES", title: "The Prince's Tale", text: "Reveals his lifetime double-agency and enduring love for Lily Potter through memories." }],
    relationships: [{ id: "lily-potter", name: "Lily Potter", type: "Eternal Love", image: "/images/characters/lily-potter.jpg" }],
    magic: [{ name: "Sectumsempra", type: "SPELL" }, { name: "Doe Patronus", type: "PATRONUS" }],
    legacy: "Executed one of the most perilous double-agent missions in history out of love."
  },
  {
    id: "rubeus-hagrid",
    number: "030",
    name: "Rubeus Hagrid",
    title: "Keeper of Keys and Grounds",
    portrait: "/images/characters/rubeus-hagrid.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Half-Giant", bloodStatus: "Part-Human", born: "6 December 1928", occupation: "Care of Magical Creatures Professor", affiliation: "Order of the Phoenix", wand: "Oak (concealed in umbrella)", patronus: "None", family: "Hagrid Family" },
    introduction: "A kind half-giant who introduces Harry to the magical world and has a deep love for magical creatures.",
    personality: "Enormously kind, fiercely loyal, gentle-hearted, passionate about dangerous beasts.",
    story: [{ year: "1991", label: "BEGINNING", title: "You're a Wizard", text: "Rescues Harry from the Dursleys and guides him to Diagon Alley." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Protector & Friend", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Pink Umbrella", type: "MAGICAL OBJECT" }],
    legacy: "The absolute soul of warm hospitality at Hogwarts."
  },
  {
    id: "filius-flitwick",
    number: "031",
    name: "Filius Flitwick",
    title: "Charms Master",
    portrait: "/images/characters/filius-flitwick.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Part-Goblin", bloodStatus: "Part-Human", born: "17 October", occupation: "Charms Professor", affiliation: "Hogwarts Staff", wand: "Unknown", patronus: "Non-corporeal", family: "Flitwick Family" },
    introduction: "The talented Charms professor and head of Ravenclaw House who later helps defend Hogwarts.",
    personality: "Cheerful, highly knowledgeable, enthusiastic, formidable duelist.",
    story: [{ year: "1998", label: "DUEL", title: "Defeated Dolohov", text: "Defeats the powerful Death Eater Antonin Dolohov during the battle." }],
    relationships: [{ id: "albus-dumbledore", name: "Albus Dumbledore", type: "Colleague", image: "/images/characters/albus-dumbledore.jpg" }],
    magic: [{ name: "Protective Charms", type: "SPELL" }],
    legacy: "Master duel-master and legendary teacher of Charms."
  },
  {
    id: "pomona-sprout",
    number: "032",
    name: "Pomona Sprout",
    title: "Herbology Professor",
    portrait: "/images/characters/pomona-sprout.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Hufflepuff", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "15 May", occupation: "Herbology Professor", affiliation: "Hogwarts Staff", wand: "Unknown", patronus: "Non-corporeal", family: "Sprout Family" },
    introduction: "The Herbology professor and head of Hufflepuff House, known for her knowledge of magical plants.",
    personality: "Nurturing, practical, earthy, and resolute.",
    story: [{ year: "1992", label: "MANDRAKES", title: "Curing the Petrified", text: "Cultivates Mandrakes to revive Basilisk victims." }],
    relationships: [{ id: "minerva-mcgonagall", name: "Minerva McGonagall", type: "Colleague", image: "/images/characters/minerva-mcgonagall.jpg" }],
    magic: [{ name: "Mandrakes", type: "PLANTS" }],
    legacy: "Weaponized dangerous flora to defend Hogwarts in battle."
  },
  {
    id: "sybill-trelawney",
    number: "033",
    name: "Sybill Trelawney",
    title: "Divination Professor",
    portrait: "/images/characters/sybill-trelawney.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Half-blood", born: "9 March", occupation: "Divination Professor", affiliation: "Hogwarts Staff", wand: "Hazlenut, unicorn hair", patronus: "Non-corporeal", family: "Trelawney Family" },
    introduction: "The Hogwarts Divination professor whose prophecy becomes closely connected to Harry and Voldemort.",
    personality: "Dramatic, eccentric, anxious, occasionally channels genuine prophecy.",
    story: [{ year: "1980", label: "PROPHECY", title: "The Chosen One Prophecy", text: "Utters the famous prophecy foretelling the demise of Voldemort." }],
    relationships: [{ id: "albus-dumbledore", name: "Albus Dumbledore", type: "Protector", image: "/images/characters/albus-dumbledore.jpg" }],
    magic: [{ name: "Inner Eye Prophecy", type: "DIVINATION" }],
    legacy: "Uttered the prophecy that shaped the destiny of the entire wizarding war."
  },
  {
    id: "remus-lupin",
    number: "034",
    name: "Remus Lupin",
    title: "Defence Against the Dark Arts Professor",
    portrait: "/images/characters/remus-lupin.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Werewolf", bloodStatus: "Half-blood", born: "10 March 1960", occupation: "Professor · Order Member", affiliation: "Order of the Phoenix · Marauders", wand: "Cypress, unicorn hair, 10¼ inches", patronus: "Wolf", family: "Lupin Family" },
    introduction: "A kind Defence professor, skilled wizard and one of James Potter's closest childhood friends.",
    personality: "Gentle, self-deprecating, deeply empathetic, exceptionally skilled.",
    story: [{ year: "1993", label: "MENTOR", title: "Teaching Patronus", text: "Teaches Harry how to cast a corporeal Patronus." }],
    relationships: [{ id: "nymphadora-tonks", name: "Nymphadora Tonks", type: "Wife", image: "/images/characters/nymphadora-tonks.jpg" }],
    magic: [{ name: "Wolfsbane Potion", type: "POTION" }, { name: "Wolf Patronus", type: "PATRONUS" }],
    legacy: "Remained a gentle soul and inspiring teacher despite a lifelong curse."
  },
  {
    id: "alastor-moody",
    number: "035",
    name: "Alastor \"Mad-Eye\" Moody",
    title: "Veteran Auror",
    portrait: "/images/characters/alastor-moody.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood", born: "Pre-1960", occupation: "Auror", affiliation: "Order of the Phoenix", wand: "Unknown", patronus: "Non-corporeal", family: "Moody Family" },
    introduction: "A famous veteran Auror known for his magical eye, experience and extreme caution.",
    personality: "Paranoid, battle-hardened, relentless, fiercely committed to fighting dark wizards.",
    story: [{ year: "1997", label: "FALL", title: "Battle of Seven Potters", text: "Fells in battle protecting the transfer of Harry Potter." }],
    relationships: [{ id: "nymphadora-tonks", name: "Nymphadora Tonks", type: "Protégé", image: "/images/characters/nymphadora-tonks.jpg" }],
    magic: [{ name: "Magical Eye", type: "MAGICAL OBJECT" }],
    legacy: "Legendary Auror responsible for filling half of Azkaban's cells."
  },
  {
    id: "dolores-umbridge",
    number: "036",
    name: "Dolores Umbridge",
    title: "Senior Undersecretary",
    portrait: "/images/characters/dolores-umbridge.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Half-blood", born: "26 August", occupation: "Ministry Official", affiliation: "Ministry of Magic", wand: "Birch, dragon heartstring, 8 inches", patronus: "Persian Cat", family: "Umbridge Family" },
    introduction: "A Ministry official who takes control of Hogwarts and uses cruel punishments against students.",
    personality: "Sadistic, authoritarian, obsessed with control, deceptively sweet.",
    story: [{ year: "1995", label: "TYRANNY", title: "High Inquisitor", text: "Establishes draconian rules and brutal punishments at Hogwarts." }],
    relationships: [{ id: "cornelius-fudge", name: "Cornelius Fudge", type: "Superior", image: "/images/characters/cornelius-fudge.jpg" }],
    magic: [{ name: "Black Quill", type: "DARK OBJECT" }],
    legacy: "Embodied institutional corruption and malicious bureaucratic tyranny."
  },
  {
    id: "horace-slughorn",
    number: "037",
    name: "Horace Slughorn",
    title: "Potions Master",
    portrait: "/images/characters/horace-slughorn.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "28 April", occupation: "Potions Professor", affiliation: "Slug Club", wand: "Cedar, dragon heartstring, 10¼ inches", patronus: "Non-corporeal", family: "Slughorn Family" },
    introduction: "A talented Potions professor whose old memory helps reveal the secret of Voldemort's Horcruxes.",
    personality: "Self-indulgent, networking-obsessed, secretly remorseful, talented.",
    story: [{ year: "1997", label: "MEMORY", title: "Unlocking the Past", text: "Surrenders his true memory about Tom Riddle's inquiry into Horcruxes." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Prize Student", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Felix Felicis Creation", type: "POTION" }],
    legacy: "Overcame personal shame to provide the crucial secret to defeating Voldemort."
  },
  {
    id: "gilderoy-lockhart",
    number: "038",
    name: "Gilderoy Lockhart",
    title: "Celebrity Author",
    portrait: "/images/characters/gilderoy-lockhart.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Half-blood", born: "26 January 1964", occupation: "Author · DADA Professor", affiliation: "Order of Merlin", wand: "Cherry, dragon heartstring, 9 inches", patronus: "Non-corporeal", family: "Lockhart Family" },
    introduction: "A famous author and professor who enjoys attention and claims to have completed many heroic adventures.",
    personality: "Vain, charismatic, fraudulent, incompetent at practical magic.",
    story: [{ year: "1992", label: "BACKFIRE", title: "Memory Backfire", text: "Accidentally wipes his own memory using Ron's broken wand." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Student Target", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Obliviate", type: "CHARM" }],
    legacy: "Cautionary tale of choosing fame over genuine magic competence."
  },
  {
    id: "quirrell",
    number: "039",
    name: "Quirinus Quirrell",
    title: "Vessel for Voldemort",
    portrait: "/images/characters/quirrell.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Half-blood", born: "26 September", occupation: "DADA Professor", affiliation: "Lord Voldemort", wand: "Alder, unicorn hair, 9 inches", patronus: "Non-corporeal", family: "Quirrell Family" },
    introduction: "Harry's first Defence professor, secretly serving Voldemort while searching for the Philosopher's Stone.",
    personality: "Timid exterior, desperate, ambitious, easily corrupted.",
    story: [{ year: "1991", label: "STONE", title: "Philosopher's Stone", text: "Carries Voldemort on the back of his head inside the underground chambers." }],
    relationships: [{ id: "voldemort", name: "Lord Voldemort", type: "Master", image: "/images/characters/voldemort.jpg" }],
    magic: [{ name: "Troll Control", type: "CHARM" }],
    legacy: "The tragic host who allowed the Dark Lord back into Hogwarts."
  },
  {
    id: "rolanda-hooch",
    number: "040",
    name: "Rolanda Hooch",
    title: "Flying Instructor & Referee",
    portrait: "/images/characters/rolanda-hooch.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "Pre-1918", occupation: "Flying Instructor", affiliation: "Hogwarts Staff", wand: "Unknown", patronus: "Non-corporeal", family: "Hooch Family" },
    introduction: "The Hogwarts flying instructor who teaches students how to use broomsticks and referees Quidditch matches.",
    personality: "Sharp-eyed, strict, fair, authoritative.",
    story: [{ year: "1991", label: "FIRST LESSON", title: "Flying Lessons", text: "Teaches Harry's year their very first broomstick flying lesson." }],
    relationships: [{ id: "oliver-wood", name: "Oliver Wood", type: "Quidditch Captain", image: "/images/characters/oliver-wood.jpg" }],
    magic: [{ name: "Broomstick Mastery", type: "SKILL" }],
    legacy: "Taught generations of young wizards how to take flight safely."
  },
  {
    id: "argus-filch",
    number: "041",
    name: "Argus Filch",
    title: "Caretaker of Hogwarts",
    portrait: "/images/characters/argus-filch.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None (Squib)", species: "Human", bloodStatus: "Squib", born: "Pre-1951", occupation: "Caretaker", affiliation: "Hogwarts Staff", wand: "None", patronus: "None", family: "Filch Family" },
    introduction: "The Hogwarts caretaker who dislikes students breaking rules and is often accompanied by Mrs Norris.",
    personality: "Bitter, vindictive, strict, obsessed with cleanliness and punishment.",
    story: [{ year: "1995", label: "RULES", title: "Inquisitorial Helper", text: "Assists Umbridge in hanging hundreds of educational decrees." }],
    relationships: [{ id: "dolores-umbridge", name: "Dolores Umbridge", type: "Ally", image: "/images/characters/dolores-umbridge.jpg" }],
    magic: [{ name: "Kwikspell Course", type: "NON-MAGICAL" }],
    legacy: "The relentless guardian of Hogwarts corridors and secret passages."
  },
  {
    id: "poppy-pomfrey",
    number: "042",
    name: "Poppy Pomfrey",
    title: "Matron of Hogwarts",
    portrait: "/images/characters/poppy-pomfrey.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "Pre-1954", occupation: "Healer / Matron", affiliation: "Hogwarts Staff", wand: "Unknown", patronus: "Non-corporeal", family: "Pomfrey Family" },
    introduction: "The Hogwarts matron who treats students injured by magical accidents, creatures and spells.",
    personality: "No-nonsense, highly caring, protective of her hospital wing peace.",
    story: [{ year: "1992", label: "BONES", title: "Regrowing Bones", text: "Regrows Harry's arm bones overnight using Skele-Gro." }],
    relationships: [{ id: "minerva-mcgonagall", name: "Minerva McGonagall", type: "Colleague", image: "/images/characters/minerva-mcgonagall.jpg" }],
    magic: [{ name: "Skele-Gro Treatment", type: "HEALING MAGIC" }],
    legacy: "Mended countless magical mishaps with unmatched medical precision."
  },

  /* =========================
     DARK FORCES
  ========================= */
  {
    id: "voldemort",
    number: "043",
    name: "Lord Voldemort",
    title: "The Dark Lord",
    portrait: "/images/characters/voldemort.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human (Mutated)", bloodStatus: "Half-blood", born: "31 December 1926", occupation: "Leader of Death Eaters", affiliation: "Death Eaters", wand: "Yew, phoenix feather, 13½ inches", patronus: "None", family: "Riddle / Gaunt Family" },
    introduction: "One of history's most dangerous Dark wizards, obsessed with immortality and control of the wizarding world.",
    personality: "Cruel, megalomaniacal, incapable of understanding love, fear-driven.",
    story: [{ year: "1995", label: "RETURN", title: "Resurrection", text: "Regains his full power and body in the graveyard ritual." }],
    relationships: [{ id: "bellatrix-lestrange", name: "Bellatrix Lestrange", type: "Lieutenant", image: "/images/characters/bellatrix-lestrange.jpg" }],
    magic: [{ name: "Avada Kedavra", type: "CURSE" }, { name: "Horcruxes", type: "DARK MAGIC" }],
    legacy: "The most feared dark wizard who tore his own soul apart for power."
  },
  {
    id: "bellatrix-lestrange",
    number: "044",
    name: "Bellatrix Lestrange",
    title: "Voldemort's Fanatical Lieutenant",
    portrait: "/images/characters/bellatrix-lestrange.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "1951", occupation: "Death Eater", affiliation: "Death Eaters", wand: "Walnut, dragon heartstring, 12¾ inches", patronus: "None", family: "Black / Lestrange Family" },
    introduction: "A powerful and dangerous witch who is fanatically loyal to Voldemort.",
    personality: "Sadistic, unhinged, fiercely devoted, lethal in dueling.",
    story: [{ year: "1998", label: "DUEL", title: "Defeated by Molly", text: "Killed in a high-stakes duel by Molly Weasley at the Battle of Hogwarts." }],
    relationships: [{ id: "voldemort", name: "Lord Voldemort", type: "Master", image: "/images/characters/voldemort.jpg" }],
    magic: [{ name: "Cruciatus Curse", type: "CURSE" }],
    legacy: "Voldemort's deadliest and most ruthless follower."
  },
  {
    id: "lucius-malfoy",
    number: "045",
    name: "Lucius Malfoy",
    title: "Death Eater Aristocrat",
    portrait: "/images/characters/lucius-malfoy.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "1954", occupation: "Ministry Governor · Death Eater", affiliation: "Death Eaters", wand: "Elm, dragon heartstring (in walking stick)", patronus: "None", family: "Malfoy Family" },
    introduction: "Draco's wealthy father, a powerful pure-blood wizard and supporter of Voldemort.",
    personality: "Arrogant, manipulative, status-obsessed, cowardly when cornered.",
    story: [{ year: "1992", label: "DIARY", title: "Planting the Diary", text: "Slips Riddle's diary into Ginny Weasley's cauldron." }],
    relationships: [{ id: "draco-malfoy", name: "Draco Malfoy", type: "Son", image: "/images/characters/draco-malfoy.jpg" }],
    magic: [{ name: "Snake-head Cane Wand", type: "WAND" }],
    legacy: "Lost his influence and pride as dark forces consumed his family."
  },
  {
    id: "narcissa-malfoy",
    number: "046",
    name: "Narcissa Malfoy",
    title: "Matriarch of House Malfoy",
    portrait: "/images/characters/narcissa-malfoy.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "1955", occupation: "Aristocrat", affiliation: "Malfoy Family", wand: "Unknown", patronus: "None", family: "Black / Malfoy Family" },
    introduction: "Draco's mother, whose love for her son eventually becomes more important than loyalty to Voldemort.",
    personality: "Proud, cold, fiercely protective of family above all else.",
    story: [{ year: "1998", label: "FOREST", title: "Lying to Voldemort", text: "Lies directly to Voldemort about Harry's death to save her son." }],
    relationships: [{ id: "draco-malfoy", name: "Draco Malfoy", type: "Son", image: "/images/characters/draco-malfoy.jpg" }],
    magic: [{ name: "Unbreakable Vow Assistance", type: "MAGIC" }],
    legacy: "Saved Harry Potter's life to secure her son's safety."
  },
  {
    id: "peter-pettigrew",
    number: "047",
    name: "Peter Pettigrew",
    title: "Wormtail",
    portrait: "/images/characters/peter-pettigrew.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "1960", occupation: "Death Eater", affiliation: "Death Eaters · Marauders", wand: "Chestnut, dragon heartstring, 9¼ inches", patronus: "None", family: "Pettigrew Family" },
    introduction: "A former friend of James Potter who betrays Harry's parents and later helps Voldemort return.",
    personality: "Cowardly, opportunistic, treacherous, parasitic.",
    story: [{ year: "1981", label: "BETRAYAL", title: "Potter Betrayal", text: "Betrays the Potters' location to Voldemort and frames Sirius Black." }],
    relationships: [{ id: "voldemort", name: "Lord Voldemort", type: "Master", image: "/images/characters/voldemort.jpg" }],
    magic: [{ name: "Rat Animagus", type: "TRANSFIGURATION" }],
    legacy: "Infamous traitor whose cowardice enabled the wizarding war."
  },
  {
    id: "barty-crouch-jr",
    number: "048",
    name: "Barty Crouch Jr.",
    title: "Fanatical Infiltrator",
    portrait: "/images/characters/barty-crouch-jr.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Pure-blood", born: "1962", occupation: "Death Eater", affiliation: "Death Eaters", wand: "Stolen Wand", patronus: "None", family: "Crouch Family" },
    introduction: "A devoted Death Eater who impersonates Mad-Eye Moody and secretly manipulates the Triwizard Tournament.",
    personality: "Cunning, fanatical, brilliantly deceptive, ruthless.",
    story: [{ year: "1994", label: "POLYJUICE", title: "Infiltrating Hogwarts", text: "Uses Polyjuice Potion to take Mad-Eye Moody's place for a full school year." }],
    relationships: [{ id: "barty-crouch-sr", name: "Barty Crouch Sr.", type: "Father", image: "/images/characters/barty-crouch-sr.jpg" }],
    magic: [{ name: "Polyjuice Deception", type: "POTION" }],
    legacy: "Successfully engineered Lord Voldemort's physical return to power."
  },
  {
    id: "fenrir-greyback",
    number: "049",
    name: "Fenrir Greyback",
    title: "Savage Werewolf",
    portrait: "/images/characters/fenrir-greyback.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Werewolf", bloodStatus: "Werewolf", born: "Pre-1945", occupation: "Snatcher / Mercenary", affiliation: "Death Eaters", wand: "Unknown", patronus: "None", family: "Greyback Family" },
    introduction: "A violent werewolf allied with Voldemort who deliberately attacks and infects other people.",
    personality: "Bloodthirsty, ruthless, predatory, savage.",
    story: [{ year: "1997", label: "TOWER", title: "Astronomy Tower", text: "Participates in the raid on Hogwarts and attacks Bill Weasley." }],
    relationships: [{ id: "voldemort", name: "Lord Voldemort", type: "Ally", image: "/images/characters/voldemort.jpg" }],
    magic: [{ name: "Werewolf Bite", type: "CURSE" }],
    legacy: "The most feared werewolf operator of the Second Wizarding War."
  },
  {
    id: "corban-yaxley",
    number: "050",
    name: "Corban Yaxley",
    title: "Head of Magical Law Enforcement",
    portrait: "/images/characters/corban-yaxley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "Pre-1970", occupation: "Death Eater · Ministry Official", affiliation: "Death Eaters", wand: "Unknown", patronus: "None", family: "Yaxley Family" },
    introduction: "A Death Eater who helps Voldemort's followers take control of the Ministry of Magic.",
    personality: "Authoritarian, cold, political, ruthless.",
    story: [{ year: "1997", label: "TAKEOVER", title: "Imperius on Thicknesse", text: "Places Minister Pius Thicknesse under the Imperius Curse to conquer the Ministry." }],
    relationships: [{ id: "voldemort", name: "Lord Voldemort", type: "Master", image: "/images/characters/voldemort.jpg" }],
    magic: [{ name: "Imperius Curse", type: "CURSE" }],
    legacy: "Infiltrated and delivered the Ministry of Magic into Voldemort's hands."
  },
  {
    id: "thorfinn-rowle",
    number: "051",
    name: "Thorfinn Rowle",
    title: "Death Eater Enforcer",
    portrait: "/images/characters/thorfinn-rowle.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Slytherin", species: "Human", bloodStatus: "Pure-blood", born: "Pre-1970", occupation: "Death Eater", affiliation: "Death Eaters", wand: "Unknown", patronus: "None", family: "Rowle Family" },
    introduction: "A dangerous Death Eater involved in attacks against Harry's allies and the Order.",
    personality: "Brutal, aggressive, imposing, reckless.",
    story: [{ year: "1997", label: "DINER", title: "Tottenham Court Attack", text: "Attacks Harry, Ron, and Hermione in a London diner." }],
    relationships: [{ id: "voldemort", name: "Lord Voldemort", type: "Master", image: "/images/characters/voldemort.jpg" }],
    magic: [{ name: "Dark Spells", type: "SPELL" }],
    legacy: "Served as a frontline combatant for the Dark Lord."
  },
  {
    id: "antonin-dolohov",
    number: "052",
    name: "Antonin Dolohov",
    title: "Master Duelist Death Eater",
    portrait: "/images/characters/antonin-dolohov.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "Pre-1950", occupation: "Death Eater", affiliation: "Death Eaters", wand: "Unknown", patronus: "None", family: "Dolohov Family" },
    introduction: "A powerful Death Eater and dangerous duelist who fights in several major battles.",
    personality: "Lethal, highly trained, cold-blooded, persistent.",
    story: [{ year: "1996", label: "MINISTRY", title: "Battle of Department of Mysteries", text: "Seriously injures Hermione with a custom purple curse." }],
    relationships: [{ id: "voldemort", name: "Lord Voldemort", type: "Master", image: "/images/characters/voldemort.jpg" }],
    magic: [{ name: "Purple Curse", type: "DARK MAGIC" }],
    legacy: "One of Voldemort's most lethal dueling champions."
  },

  /* =========================
     ORDER OF THE PHOENIX
  ========================= */
  {
    id: "sirius-black",
    number: "053",
    name: "Sirius Black",
    title: "Padfoot",
    portrait: "/images/characters/sirius-black.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "3 November 1959", occupation: "Order Member", affiliation: "Order of the Phoenix · Marauders", wand: "Unknown", patronus: "Non-corporeal", family: "Black Family" },
    introduction: "Harry's godfather, James Potter's best friend and a loyal member of the Order of the Phoenix.",
    personality: "Rebellious, intensely loyal, reckless, passionate, loving.",
    story: [{ year: "1993", label: "ESCAPE", title: "Azkaban Escape", text: "Becomes the first known person to escape Azkaban unaided." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Godson", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Dog Animagus", type: "TRANSFIGURATION" }],
    legacy: "Broke family tradition to fight dark magic and gave everything for his godson."
  },
  {
    id: "nymphadora-tonks",
    number: "054",
    name: "Nymphadora Tonks",
    title: "Metamorphmagus Auror",
    portrait: "/images/characters/nymphadora-tonks.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Hufflepuff", species: "Human (Metamorphmagus)", bloodStatus: "Half-blood", born: "1973", occupation: "Auror", affiliation: "Order of the Phoenix", wand: "Unknown", patronus: "Wolf", family: "Tonks / Black Family" },
    introduction: "A young Auror and Metamorphmagus who can naturally change her physical appearance.",
    personality: "Clumsy, joyful, courageous, fiercely devoted.",
    story: [{ year: "1998", label: "BATTLE", title: "Final Stand", text: "Fights alongside her husband Remus at the Battle of Hogwarts." }],
    relationships: [{ id: "remus-lupin", name: "Remus Lupin", type: "Husband", image: "/images/characters/remus-lupin.jpg" }],
    magic: [{ name: "Metamorphmagus Ability", type: "NATURAL MAGIC" }],
    legacy: "Brave Auror who fought heroically for a better world for her son."
  },
  {
    id: "kingsley-shacklebolt",
    number: "055",
    name: "Kingsley Shacklebolt",
    title: "Minister for Magic",
    portrait: "/images/characters/kingsley-shacklebolt.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood", born: "Pre-1960", occupation: "Senior Auror · Minister for Magic", affiliation: "Order of the Phoenix", wand: "Unknown", patronus: "Lynx", family: "Shacklebolt Family" },
    introduction: "A highly skilled Auror and Order member who becomes an important leader after the war.",
    personality: "Calm, authoritative, wise, deeply capable.",
    story: [{ year: "1997", label: "WARNING", title: "Patronus Warning", text: "Sends his Lynx Patronus to warn the wedding guests that the Ministry has fallen." }],
    relationships: [{ id: "albus-dumbledore", name: "Albus Dumbledore", type: "Leader", image: "/images/characters/albus-dumbledore.jpg" }],
    magic: [{ name: "Lynx Patronus", type: "PATRONUS" }],
    legacy: "Restored stability and equality to the Ministry of Magic as Minister."
  },
  {
    id: "arthur-weasley",
    number: "056",
    name: "Arthur Weasley",
    title: "Head of Misuse of Muggle Artifacts",
    portrait: "/images/characters/arthur-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "6 February 1950", occupation: "Ministry Employee", affiliation: "Order of the Phoenix", wand: "Unknown", patronus: "Weasel", family: "Weasley Family" },
    introduction: "Ron's father, a Ministry employee fascinated by Muggles and a loyal supporter of Harry.",
    personality: "Curious, warm, gentle-hearted, principled under pressure.",
    story: [{ year: "1995", label: "ATTACK", title: "Nagini Attack", text: "Survives a dangerous attack by Nagini in the Department of Mysteries." }],
    relationships: [{ id: "molly-weasley", name: "Molly Weasley", type: "Wife", image: "/images/characters/molly-weasley.jpg" }],
    magic: [{ name: "Weasel Patronus", type: "PATRONUS" }, { name: "Flying Ford Anglia", type: "ENCHANTED OBJECT" }],
    legacy: "Championed Muggle protection and family devotion."
  },
  {
    id: "molly-weasley",
    number: "057",
    name: "Molly Weasley",
    title: "Matriarch of House Weasley",
    portrait: "/images/characters/molly-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "30 October 1949", occupation: "Homemaker", affiliation: "Order of the Phoenix", wand: "Unknown", patronus: "Non-corporeal", family: "Weasley / Prewett Family" },
    introduction: "The loving mother of the Weasley family who treats Harry as one of her own children.",
    personality: "Fiercely protective, warm, maternal, formidable when family is threatened.",
    story: [{ year: "1998", label: "DUEL", title: "Not My Daughter", text: "Defeats Bellatrix Lestrange to protect Ginny at the Battle of Hogwarts." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Surrogate Son", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Domestic Spells & Combat Magic", type: "SPELL" }],
    legacy: "Proved that maternal love is one of the ultimate forces in magic."
  },
  {
    id: "bill-weasley",
    number: "058",
    name: "Bill Weasley",
    title: "Curse-Breaker",
    portrait: "/images/characters/bill-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human (Part-Werewolf features)", bloodStatus: "Pure-blood", born: "29 November 1970", occupation: "Gringotts Curse-Breaker", affiliation: "Order of the Phoenix", wand: "Unknown", patronus: "Non-corporeal", family: "Weasley Family" },
    introduction: "The eldest Weasley son, a Gringotts curse-breaker and husband of Fleur Delacour.",
    personality: "Cool, calm, brave, adventurous.",
    story: [{ year: "1997", label: "ATTACK", title: "Fenrir Greyback Attack", text: "Survives an attack by Greyback, acquiring wolf-like traits." }],
    relationships: [{ id: "fleur-delacour", name: "Fleur Delacour", type: "Wife", image: "/images/characters/fleur-delacour.jpg" }],
    magic: [{ name: "Curse Breaking", type: "SKILL" }],
    legacy: "Provided safe harbor for Harry at Shell Cottage during the Horcrux hunt."
  },
  {
    id: "charlie-weasley",
    number: "059",
    name: "Charlie Weasley",
    title: "Dragon Handler",
    portrait: "/images/characters/charlie-weasley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "12 December 1972", occupation: "Dragon Handler", affiliation: "Order of the Phoenix", wand: "Ash, unicorn hair", patronus: "Non-corporeal", family: "Weasley Family" },
    introduction: "Ron's older brother who works with dragons in Romania and supports the fight against Voldemort.",
    personality: "Outdoorsy, rugged, passionate about creatures, dependable.",
    story: [{ year: "1998", label: "REINFORCEMENTS", title: "Battle Reinforcements", text: "Leads reinforcements into the Battle of Hogwarts." }],
    relationships: [{ id: "ron-weasley", name: "Ron Weasley", type: "Brother", image: "/images/characters/ron-weasley.jpg" }],
    magic: [{ name: "Dragon Taming", type: "SKILL" }],
    legacy: "Brought dragon expertise and reinforcements in crucial war moments."
  },
  {
    id: "aberforth-dumbledore",
    number: "060",
    name: "Aberforth Dumbledore",
    title: "Keeper of the Hog's Head",
    portrait: "/images/characters/aberforth-dumbledore.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Half-blood", born: "1884", occupation: "Innkkeeper", affiliation: "Order of the Phoenix", wand: "Unknown", patronus: "Goat", family: "Dumbledore Family" },
    introduction: "Albus Dumbledore's younger brother who later helps Harry and his friends return to Hogwarts.",
    personality: "Cynical, practical, gruff, secretly caring.",
    story: [{ year: "1998", label: "TUNNEL", title: "Secret Passage", text: "Guards the secret passage from Hog's Head into the Room of Requirement." }],
    relationships: [{ id: "albus-dumbledore", name: "Albus Dumbledore", type: "Brother", image: "/images/characters/albus-dumbledore.jpg" }],
    magic: [{ name: "Goat Patronus", type: "PATRONUS" }],
    legacy: "Provided the vital rescue lifeline for Hogwarts rebels during the siege."
  },
  {
    id: "james-potter",
    number: "061",
    name: "James Potter",
    title: "Prongs",
    portrait: "/images/characters/james-potter.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Pure-blood", born: "27 March 1960", occupation: "Order Member", affiliation: "Order of the Phoenix · Marauders", wand: "Mahogany, 11 inches", patronus: "Stag", family: "Potter Family" },
    introduction: "Harry's father, a former Gryffindor and member of the original Order who dies protecting his family.",
    personality: "Talented, mischievous in youth, brave, fiercely protective.",
    story: [{ year: "1981", label: "DEFENSE", title: "Final Sacrifice", text: "Stands weaponless against Voldemort to buy time for his wife and child." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Son", image: "/images/characters/harry-potter.jpg" }, { id: "lily-potter", name: "Lily Potter", type: "Wife", image: "/images/characters/lily-potter.jpg" }],
    magic: [{ name: "Stag Animagus", type: "TRANSFIGURATION" }],
    legacy: "His courage live on inside Harry Potter."
  },
  {
    id: "lily-potter",
    number: "062",
    name: "Lily Potter",
    title: "Protective Mother",
    portrait: "/images/characters/lily-potter.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Human", bloodStatus: "Muggle-born", born: "30 January 1960", occupation: "Order Member", affiliation: "Order of the Phoenix", wand: "Willow, 10¼ inches", patronus: "Doe", family: "Evans / Potter Family" },
    introduction: "Harry's mother, whose sacrifice creates powerful magical protection around her son.",
    personality: "Deeply compassionate, highly talented, brave, uncompromisingly loving.",
    story: [{ year: "1981", label: "PROTECTION", title: "Sacrificial Love", text: "Refuses to step aside, creating an ancient protection charm that saves Harry." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Son", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Sacrificial Protection", type: "ANCIENT MAGIC" }],
    legacy: "Her sacrificial love became the ultimate shield that destroyed Voldemort."
  },

  /* =========================
     MINISTRY OF MAGIC
  ========================= */
  {
    id: "cornelius-fudge",
    number: "063",
    name: "Cornelius Fudge",
    title: "Minister for Magic (Former)",
    portrait: "/images/characters/cornelius-fudge.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "Pre-1964", occupation: "Minister for Magic", affiliation: "Ministry of Magic", wand: "Unknown", patronus: "Non-corporeal", family: "Fudge Family" },
    introduction: "The Minister for Magic during Harry's early Hogwarts years who refuses to accept Voldemort's return.",
    personality: "Status-conscious, complacent, fearful, easily misled.",
    story: [{ year: "1996", label: "DENIAL", title: "Seeing Voldemort", text: "Finally witnesses Voldemort's return in the Ministry atrium after a year of denial." }],
    relationships: [{ id: "dolores-umbridge", name: "Dolores Umbridge", type: "Advisor", image: "/images/characters/dolores-umbridge.jpg" }],
    magic: [{ name: "Standard Wand", type: "WAND" }],
    legacy: "His denial enabled Voldemort to rebuild his army unchecked."
  },
  {
    id: "rufus-scrimgeour",
    number: "064",
    name: "Rufus Scrimgeour",
    title: "War-time Minister for Magic",
    portrait: "/images/characters/rufus-scrimgeour.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "Pre-1960", occupation: "Minister for Magic", affiliation: "Ministry of Magic", wand: "Unknown", patronus: "Non-corporeal", family: "Scrimgeour Family" },
    introduction: "A former Auror who becomes Minister for Magic during the growing war against Voldemort.",
    personality: "Tough, battle-scarred, shrewd, defiant under torture.",
    story: [{ year: "1997", label: "DEFENCE", title: "Silent Sacrifice", text: "Refuses to give up Harry Potter's location even while being tortured to death." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Political Target", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Auror Combat Magic", type: "SPELL" }],
    legacy: "Died bravely refusing to yield Harry Potter's secrets to Voldemort."
  },
  {
    id: "pius-thickness",
    number: "065",
    name: "Pius Thicknesse",
    title: "Puppet Minister",
    portrait: "/images/characters/pius-thickness.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "Pre-1970", occupation: "Controlled Minister", affiliation: "Ministry under Death Eater Control", wand: "Unknown", patronus: "None", family: "Thicknesse Family" },
    introduction: "A Ministry official who is magically controlled and used by Voldemort's followers.",
    personality: "Controlled, rigid, emotionless under Imperius.",
    story: [{ year: "1997", label: "PUPPET", title: "Imperius Rule", text: "Ruled as Minister for Magic while completely puppeted by Corban Yaxley." }],
    relationships: [{ id: "corban-yaxley", name: "Corban Yaxley", type: "Controller", image: "/images/characters/corban-yaxley.jpg" }],
    magic: [{ name: "Controlled Wand Work", type: "SPELL" }],
    legacy: "Unwilling figurehead of the Death Eater Ministry regime."
  },
  {
    id: "barty-crouch-sr",
    number: "066",
    name: "Barty Crouch Sr.",
    title: "Head of International Magical Cooperation",
    portrait: "/images/characters/barty-crouch-sr.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Unknown", species: "Human", bloodStatus: "Pure-blood", born: "Pre-1940", occupation: "Senior Ministry Official", affiliation: "Ministry of Magic", wand: "Unknown", patronus: "Non-corporeal", family: "Crouch Family" },
    introduction: "A powerful Ministry official whose family history becomes closely connected to the Triwizard Tournament.",
    personality: "Unforgiving, strictly legalistic, ambitious, emotionally distant.",
    story: [{ year: "1995", label: "TRAGEDY", title: "Murder in the Forest", text: "Murdered by his own escaped son in the Forbidden Forest." }],
    relationships: [{ id: "barty-crouch-jr", name: "Barty Crouch Jr.", type: "Son", image: "/images/characters/barty-crouch-jr.jpg" }],
    magic: [{ name: "Polyglot Magic", type: "SKILL" }],
    legacy: "His uncompromising drive ultimately resulted in his family's destruction."
  },
  {
    id: "amelia-bones",
    number: "067",
    name: "Amelia Bones",
    title: "Head of Magical Law Enforcement",
    portrait: "/images/characters/amelia-bones.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Hufflepuff", species: "Human", bloodStatus: "Pure-blood", born: "Pre-1960", occupation: "Head of Law Enforcement", affiliation: "Ministry of Magic", wand: "Unknown", patronus: "Non-corporeal", family: "Bones Family" },
    introduction: "A respected Ministry official known for being capable, serious and fair.",
    personality: "Fair-minded, resolute, highly capable, courageous.",
    story: [{ year: "1995", label: "TRIAL", title: "Harry's Hearing", text: "Ensures Harry receives a fair hearing during his Ministry trial." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Acquaintance", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Advanced Defensive Magic", type: "SPELL" }],
    legacy: "Fought Voldemort directly in personal combat before her death."
  },

  /* =========================
     MUGGLES
  ========================= */
  {
    id: "vernon-dursley",
    number: "068",
    name: "Vernon Dursley",
    title: "Harry's Uncle",
    portrait: "/images/characters/vernon-dursley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Human", bloodStatus: "Muggle", born: "1940s", occupation: "Director at Grunnings", affiliation: "Dursley Family", wand: "None", patronus: "None", family: "Dursley Family" },
    introduction: "Harry's uncle, who strongly dislikes magic and tries to keep Harry away from the wizarding world.",
    personality: "Short-tempered, narrow-minded, intolerant of abnormality.",
    story: [{ year: "1991", label: "LETTERS", title: "Fleeing the Letters", text: "Takes his family to a remote island lighthouse to escape Hogwarts letters." }],
    relationships: [{ id: "petunia-dursley", name: "Petunia Dursley", type: "Wife", image: "/images/characters/petunia-dursley.jpg" }],
    magic: [{ name: "None", type: "NONE" }],
    legacy: "Represented extreme hostility toward magic and difference."
  },
  {
    id: "petunia-dursley",
    number: "069",
    name: "Petunia Dursley",
    title: "Harry's Aunt",
    portrait: "/images/characters/petunia-dursley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Human", bloodStatus: "Muggle", born: "Pre-1960", occupation: "Homemaker", affiliation: "Dursley Family", wand: "None", patronus: "None", family: "Evans / Dursley Family" },
    introduction: "Harry's aunt and Lily Potter's sister, who knows about magic but tries to avoid the wizarding world.",
    personality: "Resentful, envious, obsessive over normalcy, secretly heartbroken.",
    story: [{ year: "1981", label: "DOORSTEP", title: "Taking Harry In", text: "Accepts Harry onto her doorstep due to Dumbledore's letter explaining the protection." }],
    relationships: [{ id: "lily-potter", name: "Lily Potter", type: "Sister", image: "/images/characters/lily-potter.jpg" }],
    magic: [{ name: "None", type: "NONE" }],
    legacy: "Her home provided the necessary blood-based protection for Harry."
  },
  {
    id: "dudley-dursley",
    number: "070",
    name: "Dudley Dursley",
    title: "Harry's Cousin",
    portrait: "/images/characters/dudley-dursley.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Human", bloodStatus: "Muggle", born: "23 June 1980", occupation: "Boxer", affiliation: "Dursley Family", wand: "None", patronus: "None", family: "Dursley Family" },
    introduction: "Harry's spoiled cousin who bullies him when they are young but becomes less hostile later.",
    personality: "Spoiled early on, bullying, later repentant and respectful.",
    story: [{ year: "1995", label: "DEMENTOR", title: "Dementor Attack", text: "Attacked by Dementors in Little Whinging and saved by Harry." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Cousin", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "None", type: "NONE" }],
    legacy: "Reconciled with Harry, ending the bitter family feud."
  },
  {
    id: "aunt-marge",
    number: "071",
    name: "Aunt Marge",
    title: "Vernon's Sister",
    portrait: "/images/characters/aunt-marge.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Human", bloodStatus: "Muggle", born: "1950s", occupation: "Dog Breeder", affiliation: "Dursley Family", wand: "None", patronus: "None", family: "Dursley Family" },
    introduction: "Vernon's sister, who strongly dislikes Harry and insults his parents without knowing their true story.",
    personality: "Cruel, boastful, opinionated, unpleasant.",
    story: [{ year: "1993", label: "INFLATION", title: "Accidental Inflation", text: "Inflated like a balloon by Harry's accidental magic after insulting his parents." }],
    relationships: [{ id: "vernon-dursley", name: "Vernon Dursley", type: "Brother", image: "/images/characters/vernon-dursley.jpg" }],
    magic: [{ name: "None", type: "NONE" }],
    legacy: "Prompted Harry's flight from Privet Drive in 1993."
  },
  {
    id: "mr-granger",
    number: "072",
    name: "Mr. Granger",
    title: "Hermione's Father",
    portrait: "/images/characters/mr-granger.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Human", bloodStatus: "Muggle", born: "1950s", occupation: "Dentist", affiliation: "Granger Family", wand: "None", patronus: "None", family: "Granger Family" },
    introduction: "Hermione's Muggle father, a dentist who supports his daughter's life in the magical world.",
    personality: "Supportive, curious, proud father.",
    story: [{ year: "1997", label: "MEMORY", title: "Memory Modification", text: "Has his memories modified by Hermione to keep him safe in Australia." }],
    relationships: [{ id: "hermione-granger", name: "Hermione Granger", type: "Daughter", image: "/images/characters/hermione-granger.jpg" }],
    magic: [{ name: "None", type: "NONE" }],
    legacy: "Supported Hermione's integration into the magical world."
  },
  {
    id: "mrs-granger",
    number: "073",
    name: "Mrs. Granger",
    title: "Hermione's Mother",
    portrait: "/images/characters/mrs-granger.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Human", bloodStatus: "Muggle", born: "1950s", occupation: "Dentist", affiliation: "Granger Family", wand: "None", patronus: "None", family: "Granger Family" },
    introduction: "Hermione's Muggle mother who cares deeply for her daughter despite living outside the wizarding world.",
    personality: "Caring, supportive, accommodating.",
    story: [{ year: "1997", label: "PROTECTION", title: "Relocated for Safety", text: "Relocated to Australia with new identities to escape Death Eaters." }],
    relationships: [{ id: "hermione-granger", name: "Hermione Granger", type: "Daughter", image: "/images/characters/hermione-granger.jpg" }],
    magic: [{ name: "None", type: "NONE" }],
    legacy: "Sacrificed her memories of her daughter temporarily for safety."
  },

  /* =========================
     MAGICAL BEINGS & OTHERS
  ========================= */
  {
    id: "dobby",
    number: "074",
    name: "Dobby",
    title: "A Free Elf",
    portrait: "/images/characters/dobby.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "House-Elf", bloodStatus: "House-Elf", born: "28 June", occupation: "Free Hogwarts Elf", affiliation: "Harry Potter", wand: "None (Elf Magic)", patronus: "None", family: "None" },
    introduction: "A house-elf who gains his freedom and becomes an extremely loyal friend to Harry.",
    personality: "Intensely loyal, self-sacrificing, brave, freedom-loving.",
    story: [{ year: "1998", label: "HEROISM", title: "Malfoy Manor Rescue", text: "Saves Harry and friends from Malfoy Manor before giving his life." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Savior & Friend", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Elf Apparition & Telekinesis", type: "ELF MAGIC" }],
    legacy: "Died saving friends; remembered forever as a free elf."
  },
  {
    id: "kreacher",
    number: "075",
    name: "Kreacher",
    title: "House-Elf of House Black",
    portrait: "/images/characters/kreacher.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "House-Elf", bloodStatus: "House-Elf", born: "Pre-1900", occupation: "House-Elf", affiliation: "House of Black · Harry Potter", wand: "None (Elf Magic)", patronus: "None", family: "None" },
    introduction: "The old house-elf of the Black family whose loyalty changes after Harry begins treating him with respect.",
    personality: "Bitter initially, deeply loyal once respected, traditional.",
    story: [{ year: "1998", label: "CHARGE", title: "Leading the Elves", text: "Leads the Hogwarts house-elves into battle in the name of Regulus Black." }],
    relationships: [{ id: "sirius-black", name: "Sirius Black", type: "Former Master", image: "/images/characters/sirius-black.jpg" }],
    magic: [{ name: "Elf Disillusionment", type: "ELF MAGIC" }],
    legacy: "Proved that respect can transform even the bitterest heart."
  },
  {
    id: "griphook",
    number: "076",
    name: "Griphook",
    title: "Gringotts Goblin",
    portrait: "/images/characters/griphook.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Goblin", bloodStatus: "Goblin", born: "Pre-1980", occupation: "Gringotts Bank Keeper", affiliation: "Goblins", wand: "None", patronus: "None", family: "None" },
    introduction: "A Gringotts goblin who later helps Harry, Ron and Hermione enter a protected bank vault.",
    personality: "Distrustful of wizards, shrewd, opportunistic.",
    story: [{ year: "1998", label: "HEIST", title: "Gringotts Break-in", text: "Helps Harry break into Bellatrix's vault in exchange for Gryffindor's sword." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Temporary Ally", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Goblin Metal Magic", type: "GOBLIN MAGIC" }],
    legacy: "Key operative in securing Helga Hufflepuff's Cup."
  },
  {
    id: "ollivander",
    number: "077",
    name: "Garrick Ollivander",
    title: "Master Wandmaker",
    portrait: "/images/characters/ollivander.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Human", bloodStatus: "Half-blood", born: "25 September 1907", occupation: "Wandmaker", affiliation: "Ollivanders", wand: "Hornbeam, dragon heartstring, 12¾ inches", patronus: "Non-corporeal", family: "Ollivander Family" },
    introduction: "A famous wandmaker with extraordinary knowledge of wands and the witches and wizards who own them.",
    personality: "Obsessive, brilliant, impartial, single-minded.",
    story: [{ year: "1991", label: "SELECTION", title: "The Wand Chooses", text: "Matches Harry Potter with the brother wand of Lord Voldemort." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Customer", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Wandlore Expertise", type: "ANCIENT KNOWLEDGE" }],
    legacy: "The world's premier authority on wandlore."
  },
  {
    id: "viktor-krum",
    number: "078",
    name: "Viktor Krum",
    title: "Bulgarian Seeker & Champion",
    portrait: "/images/characters/viktor-krum.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Durmstrang", species: "Human", bloodStatus: "Pure-blood / Half-blood", born: "1976", occupation: "Quidditch Seeker", affiliation: "Durmstrang Institute", wand: "Hornbeam, dragon heartstring, 10¼ inches", patronus: "Non-corporeal", family: "Krum Family" },
    introduction: "A famous Bulgarian Quidditch player and Durmstrang student who competes in the Triwizard Tournament.",
    personality: "Reserved, intense, athletic, humble despite fame.",
    story: [{ year: "1994", label: "TRIWIZARD", title: "Second Task", text: "Rescues Hermione Granger during the underwater second task." }],
    relationships: [{ id: "hermione-granger", name: "Hermione Granger", type: "Yule Date", image: "/images/characters/hermione-granger.jpg" }],
    magic: [{ name: "Shark Transfiguration", type: "TRANSFIGURATION" }],
    legacy: "World-famous seeker who competed with honor."
  },
  {
    id: "fleur-delacour",
    number: "079",
    name: "Fleur Delacour",
    title: "Beauxbatons Champion",
    portrait: "/images/characters/fleur-delacour.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Beauxbatons", species: "Part-Veela", bloodStatus: "Part-Human", born: "1977", occupation: "Gringotts Employee", affiliation: "Order of the Phoenix", wand: "Rosewood, Veela hair, 9½ inches", patronus: "Non-corporeal", family: "Delacour Family" },
    introduction: "A talented Beauxbatons witch who competes in the Triwizard Tournament and later marries Bill Weasley.",
    personality: "Blunt, proud, profoundly loving and courageous.",
    story: [{ year: "1998", label: "SHELTER", title: "Shell Cottage", text: "Shelters Harry, Hermione, Ron, and Dobby after their escape." }],
    relationships: [{ id: "bill-weasley", name: "Bill Weasley", type: "Husband", image: "/images/characters/bill-weasley.jpg" }],
    magic: [{ name: "Veela Charm", type: "NATURAL MAGIC" }],
    legacy: "Proved her unconditional loyalty and deep courage during the war."
  },
  {
    id: "olympe-maxime",
    number: "080",
    name: "Olympe Maxime",
    title: "Headmistress of Beauxbatons",
    portrait: "/images/characters/olympe-maxime.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Beauxbatons", species: "Half-Giant", bloodStatus: "Part-Human", born: "Pre-1960", occupation: "Headmistress", affiliation: "Beauxbatons Academy", wand: "Unknown", patronus: "Non-corporeal", family: "Maxime Family" },
    introduction: "The impressive headmistress of Beauxbatons Academy who visits Hogwarts during the Triwizard Tournament.",
    personality: "Elegant, sensitive about her lineage, brave, dignified.",
    story: [{ year: "1995", label: "MISSION", title: "Giant Embassy", text: "Travels with Hagrid to negotiate an alliance with the giants." }],
    relationships: [{ id: "rubeus-hagrid", name: "Rubeus Hagrid", type: "Companion", image: "/images/characters/rubeus-hagrid.jpg" }],
    magic: [{ name: "Advanced Spells", type: "SPELL" }],
    legacy: "Guided Beauxbatons Academy with elegance and power."
  },
  {
    id: "nearly-headless-nick",
    number: "081",
    name: "Nearly Headless Nick",
    title: "Gryffindor House Ghost",
    portrait: "/images/characters/nearly-headless-nick.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Gryffindor", species: "Ghost", bloodStatus: "Pure-blood", born: "1400s", occupation: "House Ghost", affiliation: "Hogwarts Ghosts", wand: "None", patronus: "None", family: "de Mimsy-Porpington Family" },
    introduction: "The friendly ghost of Gryffindor House, named after his unsuccessful execution.",
    personality: "Pompous, courteous, friendly, insecure about his head attachment.",
    story: [{ year: "1992", label: "PETRIFIED", title: "Saving Justin", text: "Intercepts the Basilisk's gaze, protecting Justin Finch-Fletchley from death." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Friend", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Ghost Intangibility", type: "GHOST POWER" }],
    legacy: "A beloved companion to generations of Gryffindors."
  },
  {
    id: "grey-lady",
    number: "082",
    name: "The Grey Lady",
    title: "Helena Ravenclaw",
    portrait: "/images/characters/grey-lady.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Ghost", bloodStatus: "Pure-blood", born: "980s", occupation: "House Ghost", affiliation: "Hogwarts Ghosts", wand: "None", patronus: "None", family: "Ravenclaw Family" },
    introduction: "The ghost of Ravenclaw House and daughter of Rowena Ravenclaw, whose past helps Harry find a Horcrux.",
    personality: "Tragic, reserved, regretful, proud.",
    story: [{ year: "1998", label: "DIADEM", title: "Diadem Location", text: "Reveals the location of Rowena Ravenclaw's lost diadem to Harry." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Confidant", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Ghost Intangibility", type: "GHOST POWER" }],
    legacy: "Provided the secret needed to locate Voldemort's final Hogwarts Horcrux."
  },
  {
    id: "moaning-myrtle",
    number: "083",
    name: "Moaning Myrtle",
    title: "Bathroom Ghost",
    portrait: "/images/characters/moaning-myrtle.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "Ravenclaw", species: "Ghost", bloodStatus: "Muggle-born", born: "1928", occupation: "Hogwarts Ghost", affiliation: "Hogwarts Ghosts", wand: "None", patronus: "None", family: "Warren Family" },
    introduction: "The ghost of a Hogwarts student who usually haunts a girls' bathroom and becomes connected to several mysteries.",
    personality: "Melodramatic, sensitive, helpful when treated nicely, lonely.",
    story: [{ year: "1943", label: "DEATH", title: "First Victim", text: "Became the Basilisk's first victim, leading to Voldemort's first Horcrux." }],
    relationships: [{ id: "harry-potter", name: "Harry Potter", type: "Friend", image: "/images/characters/harry-potter.jpg" }],
    magic: [{ name: "Water Splashing Ghost Power", type: "GHOST POWER" }],
    legacy: "Her tragic death uncovered the opening of the Chamber of Secrets."
  },
  {
    id: "aragog",
    number: "084",
    name: "Aragog",
    title: "Acromantula Leader",
    portrait: "/images/characters/aragog.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Acromantula", bloodStatus: "Beast", born: "1942", occupation: "Spider Colony Leader", affiliation: "Hagrid", wand: "None", patronus: "None", family: "Acromantula Colony" },
    introduction: "A giant Acromantula raised by Hagrid who lives with a large spider colony inside the Forbidden Forest.",
    personality: "Fiercely protective of Hagrid, terrifying to others, predatory.",
    story: [{ year: "1992", label: "COLONY", title: "Forbidden Forest", text: "Explains the truth about the Chamber of Secrets to Harry and Ron." }],
    relationships: [{ id: "rubeus-hagrid", name: "Rubeus Hagrid", type: "Raiser & Friend", image: "/images/characters/rubeus-hagrid.jpg" }],
    magic: [{ name: "Venom & Webbing", type: "BEAST POWER" }],
    legacy: "His death allowed Slughorn and Harry to collect crucial Acromantula venom."
  },
  {
    id: "firenze",
    number: "085",
    name: "Firenze",
    title: "Centaur Teacher",
    portrait: "/images/characters/firenze.jpg",
    heroImage: "/images/characters/details/common-memory.png",
    identity: { house: "None", species: "Centaur", bloodStatus: "Being", born: "Pre-1980", occupation: "Divination Teacher", affiliation: "Hogwarts Staff · Centaur Herd", wand: "None", patronus: "None", family: "Forbidden Forest Herd" },
    introduction: "A centaur who helps Harry and later leaves the Forbidden Forest to teach Divination at Hogwarts.",
    personality: "Noble, calm, wise, willing to break tradition for good.",
    story: [{ year: "1991", label: "RESCUE", title: "Forest Rescue", text: "Rescues Harry from Voldemort drinking unicorn blood in the forest." }],
    relationships: [{ id: "sybill-trelawney", name: "Sybill Trelawney", type: "Co-Teacher", image: "/images/characters/sybill-trelawney.jpg" }],
    magic: [{ name: "Astrology & Divination", type: "CENTAUR MAGIC" }],
    legacy: "Bridged the gap between centaur wisdom and Hogwarts students."
  }
];

export default characterData;